config/routes.rb
Rails.application.routes.draw do

  resources :postbis

  # partie publique

  root 'accueil#index' 
   
  get 'home', to: 'home#index'

  get 'contact', to: 'accueil#contact'
  get 'infos', to: 'accueil#infos'
  get 'boutique', to: 'accueil#boutique'
 
  get 'robes_soirees', to: 'accueil#soirees'
  get 'robes_mariees', to: 'accueil#mariees'
  get 'costumes_hommes', to: 'accueil#costumes'
  get 'accessoires', to: 'accueil#accessoires'
  get 'costumes_deguisements', to: 'accueil#deguisements'

  get '/details_produit', to: 'accueil#details_produit'



   
  get 'plan', to: 'accueil#plan'
   
  # partie admin
  get 'accueil_admin', to: 'accueil_admin#index'
  get 'search', to: 'search#index'
  get 'marketing', to: 'accueil_admin#marketing'
  get 'analyses', to: 'accueil_admin#analyses'
  get 'listeSelection', to: 'accueil_admin#listeSelection'
  get 'stock', to: 'accueil_admin#stock'

  get 'selection_produit', to: 'selection_produit#index'
  get 'scanqr', to: 'selection_produit#scanqr'


  devise_for :users
   
  resources :users do
    member do
      #get :toggle_status
      get :toggle_status_user
      get :toggle_status_vendeur
      get :toggle_status_admin
      get :editer_mail
    end
  end

  resources :clients do
   # get 'import', on: :collection
    collection do 
      post :import
    end
    member do
      get :send_client_mail, 
          to: 'clients#send_client_mail', 
          as: :send_client_mail
      post :edit
      get :nouveau_client
    end
  end

  resources :fournisseurs do
    member do
      post :edit
      #get :nouveau_fournisseur
    end
  end

  resources :produits do
    collection do 
      post :import
    end
    member do
      post :edit
      get :dupliquer
    end
  end

 # resources :etiquettes
  get "/etiquettes", to: "etiquettes#index", as: :index
  get "/etiquettes/edition", to: "etiquettes#edition", as: :edition_etiquettes
  #tempo test etiquette
  #get 'etiquette', to: 'etiquettes#edition'


  resources :ensembles do
    member do 
      post :edit
    end
  end

  resources :commandes do

    member do
      get :toggle_commande_client
      get :toggle_statut_retire
      get :toggle_statut_non_retire
      get :toggle_statut_rendu

      get :toggle_edition
      get :toggle_editer

      get :generate_pdf, format: 'pdf'
      get :editer_pdf

      get :send_commande_mail, 
          to: 'commandes#send_commande_mail', 
          as: :send_commande_mail
      
      
      get :send_messagemail_mail_commande, 
          to: 'messagemails#send_messagemail_commande', 
          as: :send_messagemail_mail_commande


      post :edit
    end
  end

  resources :meetings do
    member do
      get :toggle_rendezvous_client
      post :edit
      get :editer_mail
      get :rappel_rdv
      post :invite

    end
  end 

  get 'calendar/week' => 'calendar#week', as: :calendar_week
  get 'calendar/month' => 'calendar#month', as: :calendar_month



  resources :profiles do
    member do
      post :edit
    end
  end 

  resources :ensembles do
    member do 
      post :edit
    end
  end

  resources :messagemails do
    member do 

      get :send_messagemail_commande, 
      to: 'messagemails#send_messagemail_commande', 
      as: :send_messagemail_commande

      get :editer_pdf
      get :editer_print
      get :editer_mail
     # post :edit
      
    end
  end

  resources :posts do # pour tests
    get :new_multiple, on: :collection
    post :create_multiple, on: :collection
    
    collection do 
      post :import
    end
  end

  resources :paiements do
    member do 
      post :edit
    end
  end

  resources :avoirrembs do
    member do 
      post :edit
    end
  end
  
  resources :articles do
    get :new_multiple, on: :collection
    post :create_multiple, on: :collection
    
    member do
      get :toggle_selectProduit
      get :toggle_transformer_ensemble
      post :edit
    end 
  end

  resources :sousarticles do
    get :new_multiple, on: :collection
    post :create_multiple, on: :collection
    
    member do
      get :toggle_sousarticleauto
      post :edit
    end
  end 
  
  resources :labels do
    member do
      post :edit
    end
  end 

  resources :textes do
    member do
      post :edit
    end
  end 

end

app/models/meeting.rb
class Meeting < ApplicationRecord

# interdire si rv  dejà à la meme heure
    validates :start_time, uniqueness: true

    scope :commande_courante, ->  (commande_courante) { where("commande_id = ?", commande_courante)}
    scope :client_courant, ->  (client_courant) { where("client_id = ?", client_courant)}


  def full_name
    if client_id.present?
      "#{name} - #{Client.find(client_id).full_name}"
    elsif commande_id.present?
      "#{name} - #{ Commande.find(commande_id).auto_short_name} - 
       #{Client.find(Commande.find(commande_id).client_id).full_name}" 
    else
      name 
    end 
  end
  
  def full_details
    if client_id.present?
       "#{Client.find(client_id).full_name} - #{Client.find(client_id).tel}"
    elsif commande_id.present?
       "#{Client.find(Commande.find(commande_id).client_id).full_name} - #{Client.find(Commande.find(commande_id).client_id).tel}"     
    else
              
    end 
  end

end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
#  before_action :authenticate_user!

  before_action :set_meeting, only: %i[ show edit update destroy invite ]
  #skip_before_action :authenticate_user, only: :index #permet partage cal auto sans log
 
  def index
    @meetings = Meeting.all

    @meetings_periode = Meeting.where(
      start_time: Time.now.beginning_of_month.beginning_of_week..
      Time.now.end_of_month.end_of_week)

    @meetings_a_venir = Meeting.where(
        "start_time > ?", Time.now)

    respond_to do |format|
      format.html
      format.ics do
        cal = Icalendar::Calendar.new
        cal.x_wr_calname = 'A1soir_new_app1'

        @meetings.each do | meeting |

          cal.event do |e|


           e.last_modified = Time.now.utc

           e.dtstart     = meeting.start_time 
           e.dtend       = meeting.end_time 

          # e.dtstart     = Icalendar::Values::DateTime.new(meeting.start_time, tzid: "Europe/Paris")
          # e.dtend       = Icalendar::Values::DateTime.new(meeting.end_time, tzid: "Europe/Paris")
         
           e.summary     = meeting.full_name 
            e.description = meeting.full_details
            e.location    = meeting.lieu
            e.uid         = "UNIQUEv1#{meeting.id.to_s}"
            e.sequence    = Time.now.to_i
          end
        end
        
        cal.publish
        response.headers['Content-Type'] = 'text/calendar; charset=UTF-8'
        render plain: cal.to_ical
        
      end 
    end

  end 

  def invite
    MeetingMailer.with(meeting: @meeting).invite.deliver_now
    redirect_to @meeting, notice: "invite send"
  end 


  def show
    if @meeting.commande_id.present?
      @commande = Commande.find(@meeting.commande_id)
    end
    
    if @meeting.client_id.present?
      @client = Client.find(@meeting.client_id)
    end

    respond_to do |format|
      format.html
      format.ics do
       # render plain: @meeting.to_icalendar
      #  send_data  @meeting.to_icalendar, filename: "#{@meeting.name}.ics"
      
        meeting_ics = Meetings::IcalendarEvent.new(meeting: @meeting).call
        send_data  meeting_ics, filename: "#{@meeting.name}.ics"

      end   

    end

  end


  def new
    @meeting = Meeting.new meeting_params

    @commandeId = params[:id]
    session[:commandeId] = @commandeId

    @clientId = ""
    session[:clientId] = @clientId

  end

  def edit

    @commandeId = @meeting.commande_id
    session[:commandeId] = @commandeId

    @clientId = @meeting.client_id
    session[:clientId] = @clientId

    respond_to do |format|
      format.html
      format.turbo_stream do  
        render turbo_stream: turbo_stream.update(@meeting, partial: "meetings/form", 
          locals: {meeting: @meeting})
      end
    end
  end
  
  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save

        if @meeting.commande_id.present?
          format.html { redirect_to commande_url(@meeting.commande_id), notice: "Meeting was successfully created." }
        else
          format.html { redirect_to meetings_path(), notice: "Meeting was successfully created." }
        end 
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        if @meeting.commande_id.present?
          format.html { redirect_to commande_url(@meeting.commande_id), notice: "Meeting was successfully updated." }
        else
          format.html { redirect_to meetings_path(), notice: "Meeting was successfully updated." }
        end 
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @meeting.destroy

    respond_to do |format|
      if @meeting.commande_id.present?
        format.html { redirect_to commande_url(@meeting.commande_id), notice: "Meeting was successfully destroyed." }
      else
        format.html { redirect_to meetings_url, notice: "Meeting was successfully destroyed." }
      end 
      format.json { head :no_content }
    end
  end

  def editer_mail()
    @meeting = Meeting.find(params[:id])

    MeetingMailer.with(meeting: @meeting)
    .meeting_created(@meeting).deliver_now
    flash[:notice] = "le mail RDV a bien été envoyé"
    redirect_to meeting_path(@meeting)
  end 

  def toggle_rendezvous_client
    clientId = params[:id]
    #@meeting = Meeting.create(client_id: clientId) 
    #redirect_to meeting_path(@meeting),
    #   notice: "rendez-vous client auto #{clientId}" 

    redirect_to new_meeting_path(clientId: clientId)
    
  end

  def rappel_rdv
   
   @meetings_a_venir = Meeting.where(
    "start_time > ?", Time.now)

    @meetings_a_venir.each do | meeting |
        MeetingMailer.with(meeting: meeting)
        .meeting_created(meeting).deliver_now
        flash[:notice] = "le mail rappel de RDV a bien été envoyé"
    end

   redirect_to meetings_path(),
       notice: "call meetings rappels" 
    
  end


  private
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    def meeting_params
      params.fetch(:meeting, {}).permit(:name, :start_time, :end_time, :commande_id, :client_id, :lieu)
    end
end

app/views/meetings/_footer.html.erb
    <div class="fixed-bottom footer-index text-center bg-dark">
        <div class="row justify-content-evenly">
          <div class="col-4 text-start">
            <%= link_to "", meetings_path, class:"fa-solid fa-rotate-left btn btn-sm btn-secondary" %> 
          </div>
          <div class="col-4 text-center">
            <div class="badge bg-dark">
              <%= link_to "Semaine", calendar_week_path %>
              <%= link_to "Mois", calendar_month_path %>
            </div>
          </div>
          <div class="col-4 text-end">
             <%= link_to "Nouveau", new_meeting_path, class:"btn btn-sm btn-primary m-1 p-1 fw-bold" %>
             <%#= link_to "Rappels", rappel_rdv_meeting_path(10), class:"btn btn-sm btn-warning m-1 p-1 fw-bold" %>
          </div>
        </div>
    </div>

app/views/meetings/_form.html.erb
<%= form_with(model: @meeting) do |form| %>
  <% if @meeting.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
        <% @meeting.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 
  <div class="card-body bloc-record">
    <div class="input-group mb-1">
      <%= form.label :nom, class:"input-group-text label-with-format" %>
      <%= form.text_field :name, class:"form-control field-with-format" %>
    </div>

   <% if @commandeId.present? %>
    <div class="input-group mb-1">
      <%= form.label :commande, class:"input-group-text label-with-format" %>
      <%= form.select :commande_id, Commande.all.collect { |c| [ c.nom, c.id ]}, 
            {class: 'form-control', include_blank: true, selected: @commandeId} %>
    </div>
  <% end %>

    
    <% if params[:clientId].present? %>
      <div class="input-group mb-1">
        <%= form.label :client, class:"input-group-text label-with-format" %>
        <%= form.select :client_id, Client.all.collect { |c| [ c.nom, c.id ]}, 
              {class: 'form-control', include_blank: true, selected: params[:clientId]} %>
      </div>
    <% end %>


    <div class="input-group mb-1">
      <%= form.label :début, class:"input-group-text label-with-format" %>
      <%= form.datetime_field :start_time, id: 'start_time', required: true, class:"form-control field-with-format" %>

      <%= form.label :fin, class:"input-group-text label-with-format" %>
      <%= form.datetime_field :end_time,  id: 'end_time', class:"form-control field-with-format" %>
   </div>

      <%# apres la saisie de debut meeting passer fin meeting au même jour +1h %>
      <%= render "shared/periodeMeeting" %>

    <div class="input-group mb-1">
      <%= form.label :lieu, class:"input-group-text label-with-format" %>
      <%= form.text_field :lieu, class:"form-control field-with-format" %>
    </div>
    
    <div class="text-end mt-2">
      <%= button_tag( :class => "btn btn-validate") do %>
        <i class="fa-regular fa-thumbs-up fa-bounce"></i>
      <% end %>
    </div>
 

<% end %>

app/views/meetings/_meeting.html.erb
<div id="<%= dom_id meeting %>">
  <div class="bloc-record">
    <div class="row align-items-center">

      <div class="col-10 m-0 p-2">
        <p>
          <strong>Nom:</strong>
          <%= meeting.name %>
        </p>

        <% if meeting.commande_id.present? %>
          <p>
            <strong>Commande liée:</strong>
            <%= Commande.find(meeting.commande_id).nom %>
          </p>
          <p>
            <strong>Client lié:</strong>
            <% clientId = Commande.find(meeting.commande_id).client_id %>
            <%= Client.find(clientId).full_name %>
          </p>

        <% end %>

        <% if meeting.client_id.present? %>
          <p>
            <strong>Client(e) lié(e):</strong>
            <%= Client.find(meeting.client_id).full_name %>
          </p>

        <% end %>

        <p>
          <strong>Début:</strong>
          <%= meeting.start_time.strftime("%d/%m/%y à %H:%M") if meeting.start_time.present? %> |

          <strong>Fin:</strong>
          <%= meeting.end_time.strftime("%d/%m/%y à %H:%M") if meeting.end_time.present? %>
        </p>

        <p>
          <strong>Lieu:</strong>
          <%= meeting.lieu %>
        </p>

        
      </div> 
      <div class="col-2 m-0 p-1 text-end">

      <%= link_to '', meeting_path(meeting), 
            class:"fa-regular fa-folder-open btn btn-sm btn-success mb-1" %> 
        <%= button_to "", edit_meeting_path(meeting), 
            class:"fa-regular fa-pen-to-square btn btn-sm btn-secondary mb-1", method: :post %> 
        <%= button_to '', meeting_path(meeting), 
            class:"fa-solid fa-trash-can btn btn-danger btn-sm", method: :delete %> 
      </div>

       <%# pour envoyer mail depuis meeting path %>
        <%#= link_to "", editer_mail_meeting_path(), title: "Envoyer mail",
                  class:"btn btn-sm btn-primary fa-solid fa-envelope " %>

       <%#= meeting.to_icalendar %> 

       <%# pour ajouter un rdv unique %>
       <%#= link_to "add to calendar", meeting_path(meeting, format: :ics) %> 

       <%# pour envoyer une invitation par mail au rdv unique %>
       <%#= button_to "send email invite", invite_meeting_path(meeting) %> 

    </div>
  </div>

</div>

app/views/meetings/_tempo.html.erb
<strong>tempo meetings rappels </strong>

liste des rdv à venir: 

<hr>

  <% @meetings_a_venir.each do |meeting| %>
    <div class="card-title">
        <%= meeting.name %>
    </div>
  <% end %>

app/views/meetings/edit.html.erb
<h1>Editing meeting</h1>

<%= render "form", meeting: @meeting %>

<br>

<div>
  <%= link_to "Show this meeting", @meeting %> |
  <%= link_to "Back to meetings", meetings_path %>
</div>

app/views/meetings/index.html.erb
    <div class="bloc-entete-model">
      <div class="card card-header entete-index">
        <div class="row m-0 p-0">
          <div class="col-11">
            <strong>CALENDRIER</strong> 
          </div>
          <div class="col-1 text-end m-0 p-0">
            <span class="badge rounded-pill counter-model-dashboard"><%= Meeting.count %></span>
          </div>
        </div>
      </div> 
      
    </div>

    <div class="text-center"> 

      <%= month_calendar(events: @meetings_periode) do |date, meetings| %>
        <div class="day">
          <%= date.day %>
        </div>

        <% meetings.each do |meeting| %>
          <div class="card-header">
            <div class="card-title">
              <%= link_to meeting.full_name, meeting, class:"text-primary" %>
            </div>
            <div class="card-body"> 
              <p class="card-text">
                <%= meeting.start_time.strftime("%H:%M") if meeting.start_time.present? %>
                <%= meeting.end_time.strftime('%H:%M') if meeting.end_time.present? %>
              </p>
            </div>
        <% end %>
      <% end %>

      <hr>
      <div class="text-end">
       <%= link_to "S'abonner au calendrier", meetings_url(protocol: :webcal, format: :ics), 
        class:"btn btn-sm btn-primary fw-bold" %>
      </div>
     <br> <br> <br>

    </div>

    <%= render "meetings/footer" %>
   

app/views/meetings/new.html.erb
<%= turbo_frame_tag :modal do %>
  <div data-controller="hidemodal" data-action="turbo:submit-end->hidemodal#submitEnd"> 
  
    <div class="bloc-entete-model">
      <div class="card card-header entete-index">
          <strong>Nouveau rendez-vous</strong> 
      </div>
    </div>

    <div class="bloc-record">
      <%= render "form", profile: @meeting %>
    </div>


</div>
<% end %>

app/views/meetings/show.html.erb
    <div class="bloc-entete-model">
      <div class="card card-header entete-index">
        <strong>RENDEZ-VOUS</strong> 
      </div> 
    </div>

    <%= render @meeting %>

    <% if @meeting.commande_id.present? %>
      <div class="bloc-entete-model">
        <div class="card card-header entete-index">
          <strong>COMMANDE</strong> 
        </div> 
      </div>
       <%= render @commande %>
    <% end %>

    <% if @meeting.client_id.present? %>
      <div class="bloc-entete-model">
        <div class="card card-header entete-index">
          <strong>CLIENT</strong> 
        </div> 
      </div>
       <%= render @client %>
    <% end %>




    <div class="fixed-bottom footer-index text-center bg-dark">
      <div class="row justify-content-evenly">
        <div class="col-4 text-start">
          <%= link_to "", meetings_path, class:"fa-solid fa-rotate-left btn btn-sm btn-secondary" %> 
        </div>
        <div class="col-4 text-center">
          <div class="badge bg-dark">
            <%#== pagy_nav(@pagy) %>
          </div>
        </div>
        <div class="col-4 text-end">
          <%= link_to "", meetings_path, class:"fa-solid fa-file-export btn btn-sm btn-primary" %> 
        </div>
      </div>
    </div>