config/routes.rb
Rails.application.routes.draw do

  resources :postbis

  # partie publique

  root 'accueil#index' 
   
  get 'home', to: 'home#index'

  get 'contact', to: 'accueil#contact'
  get 'infos', to: 'accueil#infos'
  get 'boutique', to: 'accueil#boutique'
 
  get 'robes_soirees', to: 'accueil#soirees'
  get 'robes_mariees', to: 'accueil#mariees'
  get 'costumes_hommes', to: 'accueil#costumes'
  get 'accessoires', to: 'accueil#accessoires'
  get 'costumes_deguisements', to: 'accueil#deguisements'

  get '/details_produit', to: 'accueil#details_produit'



   
  get 'plan', to: 'accueil#plan'
   
  # partie admin
  get 'accueil_admin', to: 'accueil_admin#index'
  get 'search', to: 'search#index'
  get 'marketing', to: 'accueil_admin#marketing'
  get 'analyses', to: 'accueil_admin#analyses'
  get 'listeSelection', to: 'accueil_admin#listeSelection'
  get 'stock', to: 'accueil_admin#stock'

  get 'selection_produit', to: 'selection_produit#index'
  get 'scanqr', to: 'selection_produit#scanqr'


  devise_for :users
   
  resources :users do
    member do
      #get :toggle_status
      get :toggle_status_user
      get :toggle_status_vendeur
      get :toggle_status_admin
      get :editer_mail
    end
  end

  resources :clients do
   # get 'import', on: :collection
    collection do 
      post :import
    end
    member do
      get :send_client_mail, 
          to: 'clients#send_client_mail', 
          as: :send_client_mail
      post :edit
      get :nouveau_client
    end
  end

  resources :fournisseurs do
    member do
      post :edit
      #get :nouveau_fournisseur
    end
  end

  resources :produits do
    collection do 
      post :import
    end
    member do
      post :edit
      get :dupliquer
    end
  end

 # resources :etiquettes
  get "/etiquettes", to: "etiquettes#index", as: :index
  get "/etiquettes/edition", to: "etiquettes#edition", as: :edition_etiquettes
  #tempo test etiquette
  #get 'etiquette', to: 'etiquettes#edition'


  resources :ensembles do
    member do 
      post :edit
    end
  end

  resources :commandes do

    member do
      get :toggle_commande_client
      get :toggle_statut_retire
      get :toggle_statut_non_retire
      get :toggle_statut_rendu

      get :toggle_edition
      get :toggle_editer

      get :generate_pdf, format: 'pdf'
      get :editer_pdf

      get :send_commande_mail, 
          to: 'commandes#send_commande_mail', 
          as: :send_commande_mail
      
      
      get :send_messagemail_mail_commande, 
          to: 'messagemails#send_messagemail_commande', 
          as: :send_messagemail_mail_commande


      post :edit
    end
  end

  resources :meetings do
    member do
      get :toggle_rendezvous_client
      post :edit
      get :editer_mail
      get :rappel_rdv
      post :invite

    end
  end 

  get 'calendar/week' => 'calendar#week', as: :calendar_week
  get 'calendar/month' => 'calendar#month', as: :calendar_month



  resources :profiles do
    member do
      post :edit
    end
  end 

  resources :ensembles do
    member do 
      post :edit
    end
  end

  resources :messagemails do
    member do 

      get :send_messagemail_commande, 
      to: 'messagemails#send_messagemail_commande', 
      as: :send_messagemail_commande

      get :editer_pdf
      get :editer_print
      get :editer_mail
     # post :edit
      
    end
  end

  resources :posts do # pour tests
    get :new_multiple, on: :collection
    post :create_multiple, on: :collection
    
    collection do 
      post :import
    end
  end

  resources :paiements do
    member do 
      post :edit
    end
  end

  resources :avoirrembs do
    member do 
      post :edit
    end
  end
  
  resources :articles do
    get :new_multiple, on: :collection
    post :create_multiple, on: :collection
    
    member do
      get :toggle_selectProduit
      get :toggle_transformer_ensemble
      post :edit
    end 
  end

  resources :sousarticles do
    get :new_multiple, on: :collection
    post :create_multiple, on: :collection
    
    member do
      get :toggle_sousarticleauto
      post :edit
    end
  end 
  
  resources :labels do
    member do
      post :edit
    end
  end 

  resources :textes do
    member do
      post :edit
    end
  end 

end

app/models/label.rb
class Label < ApplicationRecord
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :set_label, only: %i[ show edit update destroy ]

  before_action :authenticate_user!
  before_action :authenticate_vendeur_or_admin!

  # GET /labels or /labels.json
  def index
    @labels = Label.all
  end

  # GET /labels/1 or /labels/1.json
  def show
  end

  # GET /labels/new
  def new
    @label = Label.new
  end

  # GET /labels/1/edit
  def edit
    respond_to do |format|
      format.html
      format.turbo_stream do  
        render turbo_stream: turbo_stream.update(@label, partial: "labels/form", 
          locals: {label: @label})
      end
    end
  end

  # POST /labels or /labels.json
  def create
    @label = Label.new(label_params)

    respond_to do |format|
      if @label.save

        flash.now[:notice] = "le label #{@label.id} a été ajouté"

        format.turbo_stream do
           render turbo_stream: [
             turbo_stream.prepend("labels", partial: "labels/label",
             locals: {label: @label }), 
             turbo_stream.update("label_counter", Label.count),
             turbo_stream.update("flash", partial: "layouts/flash"),
           ]
        end

        format.html { redirect_to label_url(@label), notice: "label was successfully created." }
        format.json { render :show, status: :created, location: @label }
      else

        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.update('new_label', partial: "labels/form", 
              locals: {label: @label  }),
          ]
        end

        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /labels/1 or /labels/1.json
  def update
    respond_to do |format|
      if @label.update(label_params)

        format.turbo_stream do  
          render turbo_stream: turbo_stream.update(@label, partial: "labels/label", 
            locals: {label: @label})
        end

        format.html { redirect_to labels_url, notice: "label was successfully updated." }
        format.json { render :show, status: :ok, location: @label }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /labels/1 or /labels/1.json
  def destroy
    @label.destroy

    respond_to do |format|
      format.html { redirect_to labels_url, notice: "Label was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  
  def authenticate_vendeur_or_admin!
    unless current_user && (current_user.vendeur? || current_user.admin?)
      redirect_to root_path, alert: "Vous n'avez pas accès à cette page."
    end
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_label
      @label = Label.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def label_params
      params.require(:label).permit(:principale, :soiree, :mariee, :homme, :accessoire, 
          :deguisement, :info, :boutique)
    end
end

app/views/labels/_form.html.erb
<%= form_with(model: label) do |form| %>
  <% if label.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(label.errors.count, "error") %> prohibited this label from being saved:</h2>

      <ul>
        <% label.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="card-body bloc-record">
    <div class="input-group mb-1">
      <%= form.label :principale, class:"input-group-text label-with-format" %>
      <%= form.text_area :principale, class:"form-control field-with-format" %>
    </div>
    <div class="input-group mb-1">
      <%= form.label :soiree, class:"input-group-text label-with-format" %>
      <%= form.text_area :soiree, class:"form-control field-with-format" %>
    </div>
    <div class="input-group mb-1">
      <%= form.label :mariee, class:"input-group-text label-with-format" %>
      <%= form.text_area :mariee, class:"form-control field-with-format" %>
    </div>
    <div class="input-group mb-1">
      <%= form.label :homme, class:"input-group-text label-with-format" %>
      <%= form.text_area :homme, class:"form-control field-with-format" %>
    </div>
    <div class="input-group mb-1">
      <%= form.label :accessoire, class:"input-group-text label-with-format" %>
      <%= form.text_area :accessoire, class:"form-control field-with-format" %>
    </div>
    <div class="input-group mb-1">
      <%= form.label :deguisement, class:"input-group-text label-with-format" %>
      <%= form.text_area :deguisement, class:"form-control field-with-format" %>
    </div> 

    <div class="input-group mb-1">
      <%= form.label :info, class:"input-group-text label-with-format" %>
      <%= form.text_area :info, class:"form-control field-with-format" %>
    </div>  
    <div class="input-group mb-1">
      <%= form.label :boutique, class:"input-group-text label-with-format" %>
      <%= form.text_area :boutique, class:"form-control field-with-format" %>
    </div>  
 

    <div class="text-end mt-2">
      <%= button_tag( :class => "btn btn-validate") do %>
        <i class="fa-regular fa-thumbs-up fa-bounce"></i>
      <% end %>
    </div>
  </div>

<% end %>

app/views/labels/_label.html.erb
<div id="<%= dom_id label %>">
  <div class="bloc-record">
    <div class="row align-items-center">
      <div class="col-10 m-0 p-1 text-start">
         <p>
          <strong>Principale:</strong>
          <%= label.principale %>
        </p>
        <p>
          <strong>Soiree:</strong>
          <%= label.soiree %>
        </p>
        <p>
          <strong>Mariee:</strong>
          <%= label.mariee %>
        </p>
        <p>
          <strong>Homme:</strong>
          <%= label.homme %>
        </p>
        <p>
          <strong>Accessoire:</strong>
          <%= label.accessoire %>
        </p>
        <p>
          <strong>Deguisement:</strong>
          <%= label.deguisement %>
        </p>
        <p>
          <strong>Infos:</strong>
          <%= label.info %>
        </p>
        <p>
          <strong>Boutique:</strong>
          <%= label.boutique %>
        </p>

      </div> 
      <div class="col-2 m-0 p-1 text-end">
        <%#= link_to '', label_path(label), 
            class:"fa-regular fa-folder-open btn btn-sm btn-success mb-1" %> 
        <%= button_to "", edit_label_path(label), 
            class:"fa-regular fa-pen-to-square btn btn-sm btn-secondary mb-1", method: :post %> 
        <%= button_to '', label_path(label), 
            class:"fa-solid fa-trash-can btn btn-danger btn-sm", method: :delete %> 
      </div>
    </div>
  </div>

</div>

app/views/labels/edit.html.erb
<h1>Editing label</h1>

<%= render "form", label: @label %>

<br>

<div>
  <%= link_to "Show this label", @label %> |
  <%= link_to "Back to labels", labels_path %>
</div>

app/views/labels/index.html.erb
<% if current_user.admin? %>

  <div class="cadre-index mx-auto">
    <div class="bloc-entete-model">
      <div class="card card-header entete-index">
        <div class="row m-0 p-0">
          <div class="col text-center">
            <strong>LABELS</strong> 
          </div>
        </div>
      </div> 
    </div>
    <div class="bloc-record text-center fw-bold">
      <p>
        Renseignez ici les labels qui s'affichent dans les différentes rubriques du site public
      </p>
    </div>
        
    <div class="">
      <%= turbo_frame_tag :modal %>
    </div>
      
    <div class="list-records-item">
      <div id="labels">
        <%= render @labels %>
      </div>
    </div> 

  <% if @labels.count <= 0 %>
    <%= link_to "Nouveau", new_label_path, data:{turbo_frame: "modal"}, 
                class:"btn btn-sm btn-warning fw-bold m-1 p-1" %>
  <% end %>


  </div>

  <div class="fixed-bottom footer-index text-center bg-dark">
      <div class="row justify-content-evenly">
        <div class="col-4 text-start">
          <%= link_to "", labels_path, class:"fa-solid fa-rotate-left btn btn-sm btn-secondary" %> 
        </div>
        <div class="col-4 text-center">
          <div class="badge bg-dark">
            <%#== pagy_nav(@pagy) %>
          </div>
        </div>
        <div class="col-4 text-end">
          <%= link_to "", labels_path, class:"fa-solid fa-file-export btn btn-sm btn-primary" %> 
        </div>
      </div>
  </div>

  <% end %>

app/views/labels/new.html.erb
<%= turbo_frame_tag :modal do %>
  <div data-controller="hidemodal" data-action="turbo:submit-end->hidemodal#submitEnd"> 
  
    <div class="bloc-entete-model">
      <div class="card card-header entete-index">
          <strong>Nouveau label</strong> 
      </div>
    </div>


      <%= render "form", label: @label %>


</div>
<% end %>

app/views/labels/show.html.erb
<% if user_signed_in? %>

<%= render @label %>

<div>
  <%= link_to "Edit this label", edit_label_path(@label) %> |
  <%= link_to "Back to labels", labels_path %>

  <%= button_to "Destroy this label", @label, method: :delete %>
</div>

<% end %>