config/routes.rb
Rails.application.routes.draw do

  resources :postbis

  # partie publique

  root 'accueil#index' 
   
  get 'home', to: 'home#index'

  get 'contact', to: 'accueil#contact'
  get 'infos', to: 'accueil#infos'
  get 'boutique', to: 'accueil#boutique'
 
  get 'robes_soirees', to: 'accueil#soirees'
  get 'robes_mariees', to: 'accueil#mariees'
  get 'costumes_hommes', to: 'accueil#costumes'
  get 'accessoires', to: 'accueil#accessoires'
  get 'costumes_deguisements', to: 'accueil#deguisements'

  get '/details_produit', to: 'accueil#details_produit'



   
  get 'plan', to: 'accueil#plan'
   
  # partie admin
  get 'accueil_admin', to: 'accueil_admin#index'
  get 'search', to: 'search#index'
  get 'marketing', to: 'accueil_admin#marketing'
  get 'analyses', to: 'accueil_admin#analyses'
  get 'listeSelection', to: 'accueil_admin#listeSelection'
  get 'stock', to: 'accueil_admin#stock'

  get 'selection_produit', to: 'selection_produit#index'
  get 'scanqr', to: 'selection_produit#scanqr'


  devise_for :users
   
  resources :users do
    member do
      #get :toggle_status
      get :toggle_status_user
      get :toggle_status_vendeur
      get :toggle_status_admin
      get :editer_mail
    end
  end

  resources :clients do
   # get 'import', on: :collection
    collection do 
      post :import
    end
    member do
      get :send_client_mail, 
          to: 'clients#send_client_mail', 
          as: :send_client_mail
      post :edit
      get :nouveau_client
    end
  end

  resources :fournisseurs do
    member do
      post :edit
      #get :nouveau_fournisseur
    end
  end

  resources :produits do
    collection do 
      post :import
    end
    member do
      post :edit
      get :dupliquer
    end
  end

 # resources :etiquettes
  get "/etiquettes", to: "etiquettes#index", as: :index
  get "/etiquettes/edition", to: "etiquettes#edition", as: :edition_etiquettes
  #tempo test etiquette
  #get 'etiquette', to: 'etiquettes#edition'


  resources :ensembles do
    member do 
      post :edit
    end
  end

  resources :commandes do

    member do
      get :toggle_commande_client
      get :toggle_statut_retire
      get :toggle_statut_non_retire
      get :toggle_statut_rendu

      get :toggle_edition
      get :toggle_editer

      get :generate_pdf, format: 'pdf'
      get :editer_pdf

      get :send_commande_mail, 
          to: 'commandes#send_commande_mail', 
          as: :send_commande_mail
      
      
      get :send_messagemail_mail_commande, 
          to: 'messagemails#send_messagemail_commande', 
          as: :send_messagemail_mail_commande


      post :edit
    end
  end

  resources :meetings do
    member do
      get :toggle_rendezvous_client
      post :edit
      get :editer_mail
      get :rappel_rdv
      post :invite

    end
  end 

  get 'calendar/week' => 'calendar#week', as: :calendar_week
  get 'calendar/month' => 'calendar#month', as: :calendar_month



  resources :profiles do
    member do
      post :edit
    end
  end 

  resources :ensembles do
    member do 
      post :edit
    end
  end

  resources :messagemails do
    member do 

      get :send_messagemail_commande, 
      to: 'messagemails#send_messagemail_commande', 
      as: :send_messagemail_commande

      get :editer_pdf
      get :editer_print
      get :editer_mail
     # post :edit
      
    end
  end

  resources :posts do # pour tests
    get :new_multiple, on: :collection
    post :create_multiple, on: :collection
    
    collection do 
      post :import
    end
  end

  resources :paiements do
    member do 
      post :edit
    end
  end

  resources :avoirrembs do
    member do 
      post :edit
    end
  end
  
  resources :articles do
    get :new_multiple, on: :collection
    post :create_multiple, on: :collection
    
    member do
      get :toggle_selectProduit
      get :toggle_transformer_ensemble
      post :edit
    end 
  end

  resources :sousarticles do
    get :new_multiple, on: :collection
    post :create_multiple, on: :collection
    
    member do
      get :toggle_sousarticleauto
      post :edit
    end
  end 
  
  resources :labels do
    member do
      post :edit
    end
  end 

  resources :textes do
    member do
      post :edit
    end
  end 

end

app/views/shared/_dateFilter.html.erb
<div class="bloc-record p-2">
  <div class="card-body text-dark ">

    <%= form_tag url_for, method: :get do %>

      <div class="input-group mb-1">
        <%= label_tag :début, "début", class:"input-group-text label-with-format centered" %>
        <%= date_field_tag :debut, params[:debut], class:"form-control field-with-format" %>

        <%= label_tag :fin, "fin", class:"input-group-text label-with-format centered" %>
        <%= date_field_tag :fin, params[:fin], class:"form-control field-with-format" %>

        <%= link_to "Effacer", url_for(), class:"btn btn-sm btn-outline-danger rounded mx-1" %> 

        <%= submit_tag "Go", class:"btn btn-sm btn-primary rounded mx-1" %>
      </div>

    <% end %>

    <% if @datedebut.present? && @datefin.present? %>
      <div class="fw-bold">
        filtre actif: <%= @datedebut.strftime("%d/%m/%y")  %> - <%= @datefin.strftime("%d/%m/%y") %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_dateRangePicker.html.erb
<script>  

  $('#daterange').daterangepicker({
   
   // startDate: moment().add(0, 'day'),
   // endDate: moment().add(7, 'day'),

   // startDate: "",
   // endDate: "",



    "locale": {
      "format": "DD/MM/YYYY",
      "separator": " - ",
      "applyLabel": "Valider",
      "cancelLabel": "Annuler",
      "fromLabel": "De",
      "toLabel": "à",
      "customRangeLabel": "Custom",
      "daysOfWeek": [
        "Dim",
        "Lun",
        "Mar",
        "Mer",
        "Jeu",
        "Ven",
        "Sam"
      ],
      "monthNames": [
        "Janvier",
        "Février",
        "Mars",
        "Avril",
        "Mai",
        "Juin",
        "Juillet",
        "Août",
        "Septembre",
        "Octobre",
        "Novembre",
        "Décembre"
      ],
      "firstDay": 1
    },
  }, function(start, end, label) {
    // this function is called when the date range changes
    var startDate = start.format('YYYY-MM-DD');
    var endDate = end.format('YYYY-MM-DD');

    // validate that the start date and end date are not the same
    if (startDate === endDate) {
      const options = {
        message: 'Les dates de début et de fin sont identiques, êtes-vous sûr(e) de vouloir continuer ?',
        ok: 'Continuer',
        cancel: 'Annuler',
      };
      
      if (!window.confirm(options.message, options.ok, options.cancel)) {
        return;
      }
    }

    $('#start_date').val(startDate);
    $('#end_date').val(endDate);



  });
</script>

app/views/shared/_footerPublic.html.erb
<div class="fixed-bottom text-center bg-light border-top">
    <div class="row justify-content-evenly">
        <div class="col text-start">
            <%= link_to "", root_path, class:"fa fa-house btn-footer zoom a1soir-text-colored",
                title: "Accueil" %> 
        </div>
        <div class="col text-center">
            <%= link_to "", root_path, class:"fa-solid fa-cart-shopping btn-footer zoom a1soir-text-colored",
                title: "Eshop" %>
        </div>
        <div class="col text-end">
            <%= link_to "", "boutique", class:"fa-solid fa-shop btn-footer zoom a1soir-text-colored",
                title: "Boutique" %>
        </div>
        <div class="col text-end">
          <%= link_to "", "infos", class:"fa fa-circle-info btn-footer zoom a1soir-text-colored" %> 
        </div>
        <div class="col text-end">
          <%= link_to "", "/accueil_admin", class:"fa fa-user-lock btn-sm btn-footer bg-warning zoom" %>
        </div>
    </div>
</div>

app/views/shared/_navbar.html.erb
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <%= link_to image_tag("logo2.png", border: 0, width: 200), accueil_admin_path, class:"navbar-brand" %>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav navbar-responsive">
          <% if current_user %>
            <li class="nav-item">
              <%= link_to "Clients", clients_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Produits", produits_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Modèles sous articles", modelsousarticles_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Commandes", commandes_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Articles", articles_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Paiements", paiements_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Calendrier", root_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Analyses", root_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Marketing", marketing_path, class:"nav-link" %>
            </li>
              <li class="nav-item">
                <%= button_to "logout", destroy_user_session_path, method: :delete, class:"btn btn-outline-danger" %>
            </li>
          <% else %>
            <li class="nav-item">
                <%= link_to "sign up", new_user_registration_path %>
            </li>
              <li class="nav-item">
                <%= link_to "login", new_user_session_path %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

app/views/shared/_navbarHaute.html.erb
<nav class="navbar sticky-top navbar-dark navbar-expand-lg  bg-dark">
    <div class="container-fluid">
        <span class="text-left">
            <%= link_to image_tag('logo2.png', class: 'fit-image text-center'), accueil_admin_path %>
        </span>


        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    
        <div class="container-fluid">

            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">

                <ul class="navbar-nav mb-2 px-4">

                    <li class="nav-item">
                      <%= link_to(accueil_admin_path, class:"middled btn") do %>
                        <i class="fa fa-house iconcolor-nav"></i>
                        <span class="text-light fw-bold middled"> 
                          ACCUEIL 
                        </span>
                      <% end %>
                    </li>

                    <li class="nav-item">
                      <%= link_to(clients_path, class:"middled btn") do %>
                        <i class="fa fa-user iconcolor-nav"></i>
                        <span class="text-light fw-bold middled"> 
                          CLIENTS 
                        </span>
                      <% end %>
                    </li>

                    <li class="nav-item">
                      <%= link_to(produits_path, class:"middled btn") do %>
                        <i class="fa fa-shirt iconcolor-nav"></i>
                        <span class="text-light fw-bold middled"> 
                          PRODUITS 
                        </span>
                      <% end %>
                    </li>

                    <li class="nav-item">
                      <%= link_to(commandes_path, class:"middled btn") do %>
                        <i class="fa fa-file-invoice iconcolor-nav"></i>
                        <span class="text-light fw-bold middled"> 
                          COMMANDES 
                        </span>
                      <% end %>
                    </li>

                    <li class="nav-item">
                      <%= link_to(meetings_path, class:"middled btn") do %>
                        <i class="fa fa-calendar iconcolor-nav"></i>
                        <span class="text-light fw-bold middled"> 
                          CALENDRIER 
                        </span>
                        <% end %>
                    </li>

                    <li class="nav-item">
                      <%= link_to(analyses_path, class:"middled btn") do %>
                        <i class="fa fa-chart-line iconcolor-nav"></i>
                        <span class="text-light fw-bold middled"> 
                          ANALYSES 
                        </span>
                        <% end %>
                    </li>

                    <li class="nav-item">
                      <%= link_to(marketing_path, class:"middled btn") do %>
                        <i class="fa fa-bullhorn iconcolor-nav"></i>
                        <span class="text-light fw-bold middled"> 
                          MARKETING 
                        </span>
                        <% end %>
                    </li>

                </ul>
                    

            </div>
        
        </div>


    </div>
</nav>

app/views/shared/_navbarPublic.html.erb
	<nav class="navbar sticky-top navbar-expand-md navbar-light bg-light p-2 rounded">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

		<div class="collapse navbar-collapse"></div>

  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
				<ul class="navbar-nav mr-auto justify-content-center">
					<li class="nav-item active border-md-right">
            <%= link_to('robes_soirees', class:"nav-link navlink zoom-mini") do %>
              Robes de soirées 
            <% end %>
					</li>
					<li class="nav-item border-md-right">
            <%= link_to('robes_mariees', class:"nav-link navlink zoom-mini") do %>
                Robes de mariées 
            <% end %>
					</li>
					<li class="nav-item border-md-right">
            <%= link_to('costumes_hommes', class:"nav-link navlink zoom-mini") do %>
                Costumes hommes 
            <% end %>
					</li>
					<li class="nav-item border-md-right">
            <%= link_to('accessoires', class:"nav-link navlink zoom-mini") do %>
                Accessoires 
            <% end %>
					</li>
					<li class="nav-item">
            <%= link_to('costumes_deguisements', class:"nav-link navlink zoom-mini") do %>
                Costumes & Déguisements
            <% end %>
					</li>
				</ul>
			</div>

	</nav>

app/views/shared/_navbarPublicTest.html.erb
	<nav class="navbar sticky-top navbar-expand-md navbar-light bg-light p-2">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

		<div class="collapse navbar-collapse"></div>

  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">

<!-- Nav tabs -->
<ul class="nav nav-tabs">
  <li class="nav-item">
    <span class="nav-link active" data-bs-toggle="tab" href="#">
      <%= link_to 'robes de soirées', robes_soirees_path %>
    </span>
  </li>



  <li class="nav-item ">
    <a class="nav-link" data-bs-toggle="tab"  href="#">

      <%#= link_to('robes_soirees') do %>
          <span class="btn navlink"> 
          Robes de mariées 
        </span> 
      <%# end %>
    </a>
  </li>

  <li class="nav-item">
    <a class="nav-link" data-bs-toggle="tab" href="#menu2">Menu 2</a>
  </li>
</ul>


</div>

</nav>

app/views/shared/_pagy_navbar_custom.html.erb
<nav class="pagy-nav-custom" role="navigation" aria-label="pagination">
  <%== pagy_bootstrap_nav(@pagy) %>
</nav>

app/views/shared/_periodeLocation.html.erb
 <script>
    $(document).ready(function() {
      $('#start_date').change(function() {
        var startDate = new Date($(this).val()); // get value from startDate field
        if (!$('#end_date').val()) { // check if end_date is empty
          $('#end_date').val(formatDate(startDate)); // if empty pass the value of start field
        }
      });
    });

    function formatDate(date) {
      var year = date.getFullYear();
      var month = (date.getMonth() + 1).toString().padStart(2, '0');
      var day = date.getDate().toString().padStart(2, '0');
      return `${year}-${month}-${day}`;
    }

    // confirmation de validation si dates sont identiques
    $(document).ready(function() {
      $('#my-form').submit(function(event) {
        var debutloc = new Date($('#start_date').val());
        var finloc = new Date($('#end_date').val());

        if (debutloc.getTime() === finloc.getTime()) {
          var confirmMsg = 'Les dates de début et de fin sont identiques, êtes-vous sûr(e) de vouloir continuer ?';
          var result = confirm(confirmMsg);

          if (!result) {
            event.preventDefault();
          }
        }
      });
    });
</script>

app/views/shared/_periodeMeeting.html.erb
    <script>
      function formatDate(date) {
        var year = date.getFullYear();
        var month = ('0' + (date.getMonth() + 1)).slice(-2);
        var day = ('0' + date.getDate()).slice(-2);
        var hours = ('0' + date.getHours()).slice(-2);
        var minutes = ('0' + date.getMinutes()).slice(-2);
        var seconds = ('0' + date.getSeconds()).slice(-2);
        return year + '-' + month + '-' + day + 'T' + hours + ':' + minutes + ':' + seconds;
      }

      $(document).ready(function() {
        $('#start_time').change(function() {
          var startDate = new Date($(this).val()); // get value from start_time field
          startDate.setHours(startDate.getHours() + 1); // add one hour to start time
          $('#end_time').val(formatDate(startDate)); // if empty pass the value of start field
        });
      });
    </script>

app/views/shared/doc_entete.html.erb
<!DOCTYPE html> 

<html>
    <meta charset="UTF-8">
    <%= wicked_pdf_stylesheet_link_tag "application" %>
    

    <div style="position: relative; top: 10px; left: 300px;"> 
      <%#= wicked_pdf_image_tag 'logo1.png' %>
      <%= wicked_pdf_image_tag asset_url('/logo_courant.png') %> 
    </div>
    <br> <br> <hr><br>

</html>

app/views/shared/doc_footer.html.erb
<!DOCTYPE html>
<html>
    <meta charset="UTF-8">
    <%= wicked_pdf_stylesheet_link_tag "application" %>

   <br> <hr> <br>
    
    <div style="color: rgb(204, 46, 102); width: 900px; display: inline-block; text-align: center;">
       <strong> SARL AUTOUR D'UN SOIR </strong> - 27, 29 Boulevard Carnot 06400 CANNES <br>
        04 93 45 17 17 | contact@a1soir.com
    </div>

</html>