config/routes.rb
Rails.application.routes.draw do

  resources :postbis

  # partie publique

  root 'accueil#index' 
   
  get 'home', to: 'home#index'

  get 'contact', to: 'accueil#contact'
  get 'infos', to: 'accueil#infos'
  get 'boutique', to: 'accueil#boutique'
 
  get 'robes_soirees', to: 'accueil#soirees'
  get 'robes_mariees', to: 'accueil#mariees'
  get 'costumes_hommes', to: 'accueil#costumes'
  get 'accessoires', to: 'accueil#accessoires'
  get 'costumes_deguisements', to: 'accueil#deguisements'

  get '/details_produit', to: 'accueil#details_produit'



   
  get 'plan', to: 'accueil#plan'
   
  # partie admin
  get 'accueil_admin', to: 'accueil_admin#index'
  get 'search', to: 'search#index'
  get 'marketing', to: 'accueil_admin#marketing'
  get 'analyses', to: 'accueil_admin#analyses'
  get 'listeSelection', to: 'accueil_admin#listeSelection'
  get 'stock', to: 'accueil_admin#stock'

  get 'selection_produit', to: 'selection_produit#index'
  get 'scanqr', to: 'selection_produit#scanqr'


  devise_for :users
   
  resources :users do
    member do
      #get :toggle_status
      get :toggle_status_user
      get :toggle_status_vendeur
      get :toggle_status_admin
      get :editer_mail
    end
  end

  resources :clients do
   # get 'import', on: :collection
    collection do 
      post :import
    end
    member do
      get :send_client_mail, 
          to: 'clients#send_client_mail', 
          as: :send_client_mail
      post :edit
      get :nouveau_client
    end
  end

  resources :fournisseurs do
    member do
      post :edit
      #get :nouveau_fournisseur
    end
  end

  resources :produits do
    collection do 
      post :import
    end
    member do
      post :edit
      get :dupliquer
    end
  end

 # resources :etiquettes
  get "/etiquettes", to: "etiquettes#index", as: :index
  get "/etiquettes/edition", to: "etiquettes#edition", as: :edition_etiquettes
  #tempo test etiquette
  #get 'etiquette', to: 'etiquettes#edition'


  resources :ensembles do
    member do 
      post :edit
    end
  end

  resources :commandes do

    member do
      get :toggle_commande_client
      get :toggle_statut_retire
      get :toggle_statut_non_retire
      get :toggle_statut_rendu

      get :toggle_edition
      get :toggle_editer

      get :generate_pdf, format: 'pdf'
      get :editer_pdf

      get :send_commande_mail, 
          to: 'commandes#send_commande_mail', 
          as: :send_commande_mail
      
      
      get :send_messagemail_mail_commande, 
          to: 'messagemails#send_messagemail_commande', 
          as: :send_messagemail_mail_commande


      post :edit
    end
  end

  resources :meetings do
    member do
      get :toggle_rendezvous_client
      post :edit
      get :editer_mail
      get :rappel_rdv
      post :invite

    end
  end 

  get 'calendar/week' => 'calendar#week', as: :calendar_week
  get 'calendar/month' => 'calendar#month', as: :calendar_month



  resources :profiles do
    member do
      post :edit
    end
  end 

  resources :ensembles do
    member do 
      post :edit
    end
  end

  resources :messagemails do
    member do 

      get :send_messagemail_commande, 
      to: 'messagemails#send_messagemail_commande', 
      as: :send_messagemail_commande

      get :editer_pdf
      get :editer_print
      get :editer_mail
     # post :edit
      
    end
  end

  resources :posts do # pour tests
    get :new_multiple, on: :collection
    post :create_multiple, on: :collection
    
    collection do 
      post :import
    end
  end

  resources :paiements do
    member do 
      post :edit
    end
  end

  resources :avoirrembs do
    member do 
      post :edit
    end
  end
  
  resources :articles do
    get :new_multiple, on: :collection
    post :create_multiple, on: :collection
    
    member do
      get :toggle_selectProduit
      get :toggle_transformer_ensemble
      post :edit
    end 
  end

  resources :sousarticles do
    get :new_multiple, on: :collection
    post :create_multiple, on: :collection
    
    member do
      get :toggle_sousarticleauto
      post :edit
    end
  end 
  
  resources :labels do
    member do
      post :edit
    end
  end 

  resources :textes do
    member do
      post :edit
    end
  end 

end

app/models/sousarticle.rb
class Sousarticle < ApplicationRecord
  belongs_to :article
  #validates :nature, presence: true

 # enum natures: ["retouches", "ceinture", "chaussures", 
              #  "nœud papillon", "veste", "pantalon", 
              #  "chemise", "pochette", "boutons de manchette",
              #  "gilet", "autre"]

  scope :article_courant, ->  (article_courant) { where("article_id = ?", article_courant)}
  scope :produit_courant, ->  (produit_courant) { where("sousarticles.produit_id = ?", produit_courant)}

  scope :sousarticlesLoues, -> { joins(:article).where("locvente = ?", "location")}
  scope :sousarticlesVendus, -> { joins(:article).where("locvente = ?", "vente")}


  scope :locvente, -> (locvente_value) { joins(:article).where("locvente = ?", locvente_value ) }
  
  scope :hors_devis, -> { where(article_id: Article.joins(:commande).where("devis = ?", false))}

 # scope :exclude_devis_commandes, -> {
 #   where.not(article_id: Article.joins(:commandes)
 #                               .where(commandes: { devis: false })
 #                               .pluck(:id))
 # }

 scope :a_venir, -> { joins(article: :commande).where('commandes.finloc >= ?', Date.current) }
 scope :termine, -> { joins(article: :commande).where('commandes.finloc <= ?', Date.current) }


  scope :sum_sousarticles, -> {sum('prix_sousarticle')}
  scope :sum_caution_sousarticles, -> {sum('caution_sousarticle')}
  scope :compte_sousarticles, -> {count('nature')}


    # filtres analyses
    scope :filtredatedebut, -> (debut) { where("sousarticles.created_at >= ?", debut) }
    scope :filtredatefin, -> (fin) { where("sousarticles.created_at <= ?", fin) }
     
  def texte_record
    "#{nature} | prix " "#{prix_sousarticle}" " € | description " "#{description}"
  end

 

end

app/controllers/sousarticles_controller.rb
class SousarticlesController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_vendeur_or_admin!

  before_action :set_sousarticle, only: %i[ show edit update destroy ]

  def index
    @sousarticles = Sousarticle.all
  end

  def show
  end

  def new
    @sousarticle = Sousarticle.new sousarticle_params

    @articleId = params[:articleId]
    session[:articleId] = params[:articleId]

    @produitId = params[:produitId]

    @typelocvente = ["location", "vente"]
   # @natures = Modelsousarticle.distinct.pluck(:nature)

    if @produitId.present? && @articleId.present?
      if Article.find(@articleId).locvente == "location"
        @valPrix = Produit.find(@produitId).prixlocation
      else
        @valPrix = Produit.find(@produitId).prix
      end
    end

    categorieVal = params[:categorieVal]
    couleurVal = params[:couleurVal]

    if categorieVal.present?
      @produits = Produit.categorie_selected(categorieVal)
      @couleurs = Produit.categorie_selected(categorieVal).distinct.pluck(:couleur)
        if couleurVal.present?
          @produits = Produit.categorie_selected(categorieVal).couleur_selected(couleurVal)
        end
    else
      @produits = Produit.all 
    end
    

  end

  def new_multiple

    @commandeId =  session[:commandeId]
    @articleId = params[:articleId]
    session[:articleId] = params[:articleId]
    @articleLocVente = Article.find(@articleId).locvente
    @typelocvente = ["location", "vente"]

    @produits_ids = Produit.find(params[:produits_ids])
    @nbElements = params[:nbElements].to_i
    
    @sousarticles = []
    @nbElements.times { @sousarticles << Sousarticle.new }
  end

  def edit
  
    @produitId = params[:produitId]

   # @articleId = params[:articleId]
    #session[:articleId] = params[:articleId]

  #  @natures = Modelsousarticle.distinct.pluck(:nature)
  #  @produitId = params[:produitId]

     respond_to do |format|
      format.html
      format.turbo_stream do  
        render turbo_stream: turbo_stream.update(@sousarticle, partial: "sousarticles/form", 
          locals: {sousarticle: @sousarticle})
      end
    end

  end

  def create
    @articleId = params[:articleId]
    @sousarticle = Sousarticle.new(sousarticle_params)
    @commandeId = session[:commandeId]

   # @produitId = Article.find(@sousarticle.article_id).produit_id

    permitted_array = [:article_id, :produit_id, :prix_sousarticle, :caution_sousarticle, :commentaire]
    if params[:sousarticle]
      Sousarticle.create(params[:sousarticle].permit(permitted_array))
    else
      params[:sousarticles].each do |index, sousarticle_params|
        Sousarticle.create(sousarticle_params.permit(permitted_array))
      end
    end
    redirect_to commande_path(@commandeId)

   # respond_to do |format|
   #   if @sousarticle.save
   #     format.html { redirect_to article_path(@sousarticle.article_id, commandeId: @commandeId, produitId:  @produitId), 
   #          notice: "Sousarticle was successfully created." }
   #     format.json { render :show, status: :created, location: @sousarticle }
   #   else
   #     format.html { render :new, status: :unprocessable_entity }
   #     format.json { render json: @sousarticle.errors, status: :unprocessable_entity }
   #   end
   # end
  end

  def update
    @commandeId = Article.find(@sousarticle.article_id).commande_id
    @produitId = Article.find(@sousarticle.article_id).produit_id
   # @natures = Modelsousarticle.distinct.pluck(:nature)
    @articleId = params[:articleId]

    respond_to do |format|
      if @sousarticle.update(sousarticle_params)

        format.turbo_stream do  
          render turbo_stream: turbo_stream.update(@sousarticle, partial: "sousarticles/sousarticle",
             locals: {sousarticle: @sousarticle})
        end

        format.html { redirect_to edit_article_path(@sousarticle.article_id, commandeId: @commandeId, produitId:  @produitId), 
            notice: "Sousarticle was successfully updated." }

      #  format.html { redirect_to article_path(@sousarticle.article_id, commandeId: @commandeId, produitId:  @produitId), 
      #  notice: "Sousarticle was successfully updated." }
             
        format.json { render :show, status: :ok, location: @sousarticle }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sousarticle.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy

    @commandeId = Article.find(@sousarticle.article_id).commande_id
    @produitId = Article.find(@sousarticle.article_id).produit_id

    @sousarticle.destroy

    respond_to do |format|
      format.html { redirect_to edit_article_path(@sousarticle.article_id, commandeId: @commandeId, produitId:  @produitId), 
        notice: "Sousarticle was successfully destroyed." }
      format.json { head :no_content }
    end
  end



  private

  def authenticate_vendeur_or_admin!
    unless current_user && (current_user.vendeur? || current_user.admin?)
      redirect_to root_path, alert: "Vous n'avez pas accès à cette page."
    end
  end

    def set_sousarticle
      @sousarticle = Sousarticle.find(params[:id])
    end

    def sousarticle_params
      params.fetch(:sousarticle, {}).permit(:article_id, :produit_id, :nature, :description, 
        :prix_sousarticle, :caution_sousarticle, :taille, :commentaire)
    end
end

app/views/sousarticles/_form.html.erb
<%= form_with(model: sousarticle) do |form| %>
  <% if sousarticle.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(sousarticle.errors.count, "error") %> prohibited this sousarticle from being saved:</h2>

      <ul>
        <% sousarticle.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div>
      <% form.label :article_id, style: "display: block" %>
      <% if sousarticle.persisted? %>
        <%= form.hidden_field :article_id %>
      <% else %>
        <%= form.hidden_field :article_id, value: @articleId %>
      <% end %>
    </div>

    <div>
      <% form.label :produit_id, style: "display: block" %>
      <%#= form.select :article_id, Article.all.collect { |a| [ a.id, a.id ] },  include_blank: true %>
      <%= form.hidden_field(:produit_id, value: @produitId) %>
    </div>

    <%# if @produitId.present? %> 
      
      <div class="bloc-entete-model">
        <div class="card-body p-1">
          <div class="row p-0 m-0">
            <div class="col cadre-interieur">
              <%= render "selection_produit/produitLie" %> <br>
            </div>
            <div class="col cadre-interieur"> 
              <div data-controller="form-element">
                <%= form.button "Validate", formaction: new_sousarticle_path(commandeId: @commandeId, produitId: @produitId, 
                articleId: @articleId), formmethod: :get, data: { turbo_frame: :total_field, form_element_target: "submitbtn" } %> 
      
                <div class="input-group input-group-sm mb-2 justify-content-center">
                    <%= form.label :prix, class:"input-group-text bg-secondary text-light label-sized" %>

                     <% if sousarticle.persisted? %>
                        <%= form.number_field :prix_sousarticle, class:"form-control text-center input-sized" %>
                     <% else %>
                      <%= form.number_field :prix_sousarticle, { data: { action: "change->form-element#remotesubmit"}, 
                          value: @valPrix, class:"form-control text-center input-sized"} %>
                     <% end %>
                </div>

                <div class="input-group input-group-sm mb-2 justify-content-center">
                  <%= form.label :commentaire, class:"input-group-text bg-primary text-light label-sized" %>
                  <%= form.text_area :commentaire, class:"form-control text-dark input-sized" %>
                </div>


              </div>

      <%# end %>
                
                    <%= turbo_frame_tag :total_field do %>
                      <%# valQuantite = form.object.quantite %>
                      <% valPrix = form.object.prix_sousarticle.to_d %>
                      <% produitId = form.object.produit_id %>
                      <%# typeLocVente = form.object.locvente %>



                         <%# if @produitId.present? %> 
                          <div class="input-group input-group-sm mb-1 justify-content-center">
                            <%#= form.label :total, class:"input-group-text bg-dark text-light label-sized" %>

                              <%# if sousarticle.persisted? %>
                                <%#= form.number_field :total, class:"form-control bg-dark text-white text-center input-sized" %>
                              <%# else %>
                                <%#= form.number_field :total, value:  valPrix, class:"form-control bg-dark text-white text-center input-sized" %>
                              <%# end %>
                          
                          </div> 

                            
                          <div class="text-center text-bottom p-2 me-3">
                          
                              <%= link_to 'Annuler', new_sousarticle_path(commandeId: @commandeId), class:"btn btn-outline-danger btn-sm" %>
                              <%= form.submit "Créer", class: 'btn btn-sm btn-success' %>

                          </div>
                        <%# end %>  
                   
                    <% end %>

                </div>
            </div>
        </div> 

    </div>

  <% end %>

app/views/sousarticles/_nouveauSousarticle.html.erb
<div data-controller="nouveau", class="my-0">
  <div role="button" data-action="click->nouveau#openNouveau" data-nouveau-target="openNouveau", 
       class="btn btn-sm btn-warning", style="inline;">
       Nouveau
  </div>
  <div role="button" data-action="click->nouveau#closeNouveau" data-nouveau-target="closeNouveau", 
       class="btn btn-sm btn-danger", style="inline;">
       Fermer
  </div>
  <div id="new_sousarticle">
    <div data-nouveau-target="nouveauContent">
        <%= render partial: "sousarticles/form", locals: {sousarticle: Sousarticle.new} %>
    </div>
  </div>

</div>

app/views/sousarticles/_sousarticle.html.erb
<div id="<%= dom_id sousarticle %>">

  <div class="cadre-interieur">
    <div class="row p-0 m-0 text-dark align-items-center">

      <div class="col-4 m-0">  
         <%= image_tag(Produit.find(sousarticle.produit_id).default_image, 
              style:"width: 50px;", class:"img-fluid rounded-start bg-white") %> 
      </div>

      <div class="col-5 m-0 ">  
        <%= Produit.find(sousarticle.produit_id).nom %> | 
        <%= sousarticle.prix_sousarticle %> |
        <%= Produit.find(sousarticle.produit_id).taille %> |
        <%= sousarticle.commentaire %>
      </div>

      <%# @commandeId = Article.find(sousarticle.article_id).commande_id %>


      <div class="col-3 p-0 m-0 text-end">
        <%= button_to "", edit_sousarticle_path(sousarticle, articleId: sousarticle.article_id, produitId: sousarticle.produit_id), 
              class:"fa-regular fa-pen-to-square btn btn-sm btn-secondary", method: :post %>

        <%= button_to '', sousarticle_path(sousarticle), 
            class:"fa-solid fa-trash-can btn btn-danger btn-sm", method: :delete %> 
      </div>
    </div>
  </div>

</div>

app/views/sousarticles/_sousarticlesLies.html.erb
 
<div class="bloc-record bg-light">

  <div id="sousarticles">
    <%= render @sousarticles %>
  </div>

  <div class="text-end p-2">
    <%= link_to "Nouveau", selection_produit_path(commandeId: params[:commandeId], articleId: @article), 
             class:"btn btn-sm btn-primary fw-bold mt-0 mb-0" %>
  </div>

</div>

app/views/sousarticles/edit.html.erb
<h1 class="text-dark">Editing sousarticle</h1>

<%= render "form", sousarticle: @sousarticle %>

<br>

<div>
  <%= link_to "Show this sousarticle", @sousarticle %> |
  <%= link_to "Back to sousarticles", sousarticles_path %>
</div>

app/views/sousarticles/index.html.erb
<% if user_signed_in? %>

  <h1>SOUS-ARTICLES</h1>

  <div id="sousarticles">
    <% @sousarticles.each do |sousarticle| %>
      <%= render sousarticle %>
      <p>
        <%#= link_to "Show this sousarticle", sousarticle %>
      </p>
    <% end %>
  </div>

  <%= link_to "New sousarticle", new_sousarticle_path %>

<% end %>

app/views/sousarticles/new.html.erb
<% if session[:commandeId].present? %>
  <% @commandeId = session[:commandeId] %>
<% else %>
  <% @commandeId = params[:commandeId] %>
<% end %>

<% @clientId = Commande.find(@commandeId).client_id if @commandeId.present? %>

<div class="bloc-entete-model">
  <div class="card card-header entete-index m-0 p-1">
   
      <h3 class="text-center fw-bold m-0 p-1"> Nouveau sous-article </h3>
      <div class="text-end m-0 p-1">
        <span class="badge text-bg-primary"> <%= Produit.find(Article.find(@articleId).produit_id).nom if @articleId.present? %> </span> 
        <span class="badge text-bg-secondary"> <%= Commande.find(@commandeId).texte_record if @commandeId.present? %> </span> 
        <span class="badge text-bg-secondary"> <%= Client.find(@clientId).full_name if @clientId.present? %> </span> 
      </div>
 
  </div>
</div>

<div class="card"> <%= render "selection_produit/search" %> </div>
<div class="card my-1"> <%= render "selection_produit/choixCategorie" %> </div>


<%# liste des produits pour selection %>
<div class="bloc-record">
  <% unless @produitId.present? %> 
    <%= render "selection_produit/listeSelection" %>
  <% end %>

  <%= render "form", sousarticle: @sousarticle %>


</div>

app/views/sousarticles/new_multiple.html.erb
<%= form_tag sousarticles_path, method: :post do %>
  <% @sousarticles.each_with_index do |sousarticle, index| %>
    <%= fields_for "sousarticles[#{index}]", sousarticle do |sousarticle_fields| %>

      <% if @produits_ids.present? %>

        <div class="bloc-entete-model card-body p-1">
          <div class="row p-0 m-0 justify-content-center">
            <div class="col-md-10 cadre-interieur"> 

                <%= sousarticle_fields.hidden_field(:article_id, value: @articleId) %>
                <%= sousarticle_fields.hidden_field(:produit_id, value: @produits_ids[index].id) %>
                
                <div class="row">
                  <div class="col">
                    <h5 class="card-title text-dark me-4 text-center">
                      Sous Article #<%= index + 1 %> 
                      <span class="text-left text-dark fw-bold">
                        <%= @produits_ids[index].nom %>
                      </span>
                    </h5>
                    <div class="text-center m-1 p-1">
                      <%= image_tag @produits_ids[index].image1, width: "120", class:"rounded shadowed" if @produits_ids[index].image1.attached? %>
                    </div>
                  </div>

                  <div class="col">

                    <% if @articleLocVente == "location" %>
                      <% prixSousArticle = @produits_ids[index].prixlocation %>
                      <% cautionSousArticle = @produits_ids[index].caution %>
                    <% else %>
                      <% prixSousArticle = @produits_ids[index].prix %>
                      <% cautionSousArticle = 0 %>
                    <% end %>

                    <div class="input-group input-group-sm mb-2 justify-content-center">
                      <%= sousarticle_fields.label :prix, class:"input-group-text bg-secondary text-light label-sized" %>
                      <%= sousarticle_fields.number_field :prix_sousarticle, value: prixSousArticle, 
                        class:"form-control text-center input-sized" %> <br>
                    </div>

                  <% if @articleLocVente == "location" %>
                    <div class="input-group input-group-sm mb-2 justify-content-center" data-totalupdate-target="containerCaution">
                      <%= sousarticle_fields.label :caution, class:"input-group-text bg-secondary text-light label-sized" %>
                      <%= sousarticle_fields.number_field :caution_sousarticle, value: cautionSousArticle, 
                          class:"form-control bg-secondary text-white text-center input-sized" %> <br>
                    </div>
                  <% end %>

                  
                    <div class="input-group input-group-sm mb-2 justify-content-center">
                      <%= sousarticle_fields.label :commentaire, class:"input-group-text bg-primary text-light label-sized" %>
                      <%= sousarticle_fields.text_area :commentaire, class:"form-control text-dark input-sized" %>
                    </div>

                  </div>
                </div>
             
            </div>
          </div>
        </div>

      <% end %> 
    <% end %> <hr>
  <% end %>
  <%= submit_tag 'Créer sous articles', class:"btn btn-success" %>
<% end %>

app/views/sousarticles/show.html.erb
<% if user_signed_in? %>

<%= render @sousarticle %>

<div>
  <%= link_to "Edit this sousarticle", edit_sousarticle_path(@sousarticle) %> |
  <%= link_to "Back to sousarticles", sousarticles_path %>

  <%= button_to "Destroy this sousarticle", @sousarticle, method: :delete %>
</div>

<% end %>